"""Previewed, reversible consolidation of companion documents (not official specs)."""
from __future__ import annotations

import json
import os
from pathlib import Path
import re
import shutil
import urllib.parse

from .common import WorkbenchError, atomic_write, inside, json_text, load_project, project_lock, sha
from .layout import COMPACT, DOCUMENTS, compact, destination
from .trace import inspect, parse_file
from .approval_core import DEPENDENCY_LINKS, load_events
from . import VERSION

ROOT = Path(__file__).resolve().parents[1]
LINK = re.compile(r'(\]\()([^\s)]+)([^)]*\))')


def slug(text: str) -> str:
    return re.sub(r'[^\w\- ]', '', text.lower()).replace(' ', '-')


def migrate(root: Path, apply: bool = False, include: list[str] | None = None) -> dict:
    config = load_project(root)
    if compact(config):
        return {'applied': False, 'already_compact': True, 'documents': config['required_docs']}
    result = inspect(root, 'draft')
    # Incomplete drafts are movable, but malformed IDs/JSON/links are not.
    allowed = {'NO_ITEMS', 'LEGACY_APPROVAL_UNBOUND', 'STALE_APPROVAL', 'STALE_DEPENDENCY_APPROVAL',
               'APPROVAL_METADATA_MISMATCH', 'APPROVAL_STATUS_MISMATCH', 'APPROVAL_REVOKED',
               'APPROVAL_MISSING', 'APPROVAL_INVALID'}
    bad = [f for f in result['findings'] if f['severity'] == 'error' and f['code'] not in allowed]
    if bad:
        raise WorkbenchError('移行前に構造エラーを修正してください: '+', '.join(f['code'] for f in bad[:8]))
    events = load_events(root)  # Validate the ledger; never rewrite or reapprove it.
    docs = config['docs_dir']
    legacy = json.loads((ROOT/'assets/templates/legacy-manifest.json').read_text())
    known = {k.replace('@DOCS@', docs) for k in legacy if k.startswith('@DOCS@/')}
    sources = {p for p in known if inside(root, p).is_file()}
    # Default item files created by the old CLI have a single ID matching the name.
    for row in result['items']:
        path = row['_file']
        if path == docs+'/items/'+row['id']+'.md' and sum(r['_file']==path for r in result['items']) == 1:
            sources.add(path)
    for path in include or []:
        if path.startswith(('specs/', '.specify/')) or not path.startswith(docs+'/'):
            raise WorkbenchError('--include-docは上流文書内のユーザー文書だけを指定できます')
        if not inside(root, path).is_file() or not path.endswith('.md'):
            raise WorkbenchError('移行するMarkdownがありません: '+path)
        sources.add(path)
    destinations = {name: docs+'/'+name for name in DOCUMENTS}
    for target in destinations.values():
        if inside(root, target).exists():
            raise WorkbenchError('統合先に既存ファイルがあります。上書きしません: '+target)
    records = {}
    reviews=inside(root,docs+'/governance/reviews')
    if reviews.exists():
        for path in sorted(reviews.glob('rev-*.json')):
            obj=json.loads(path.read_text('utf-8'))
            if not isinstance(obj,dict) or obj.get('generator')!='speckit-workbench-review':
                continue
            if obj.get('review_id')!=path.stem:
                raise WorkbenchError('レビュー記録のIDが一致しません: '+str(path))
            from .approval import load_review
            packet=load_review(root,path.stem)
            if packet.get('schema_version')!=1 or not isinstance(packet.get('items'),list):
                raise WorkbenchError('レビュー記録の構造が壊れています: '+str(path))
            fingerprint=packet.get('review_fingerprint')
            if fingerprint and fingerprint!=sha(json.dumps({k:v for k,v in packet.items() if k!='review_fingerprint'},
                    ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()):
                raise WorkbenchError('レビュー記録の指紋が一致しません: '+str(path))
            for old in (path,path.with_suffix('.md')):
                if old.is_file():
                    records[old.relative_to(root).as_posix()]='.specify/workbench/reviews/'+old.name
    derived=set()
    for suffix in ('traceability/index.json','traceability/matrix.md','governance/approvals.md'):
        rel=docs+'/'+suffix;path=inside(root,rel)
        if path.is_file():
            text=path.read_text('utf-8')
            owned=(json.loads(text).get('generator')=='speckit-workbench' if path.suffix=='.json'
                   else text.startswith('<!-- Generated by speckit-workbench -->'))
            if owned:
                derived.add(rel)
    for target in records.values():
        if inside(root,target).exists():
            raise WorkbenchError('内部記録の移行先に既存ファイルがあります: '+target)
    cfgpath = '.specify/workbench.json'
    removed=sources|set(records)|derived
    originals = {p:inside(root, p).read_bytes() for p in removed|{cfgpath}}
    digest = sha(b''.join(p.encode()+sha(data).encode() for p,data in sorted(originals.items())))[:20]
    backup = '.specify/workbench/migrations/compact-'+digest
    mapping = dict(records)
    mapping.update({p:backup+'/original/'+p for p in derived})
    bodies = {}
    for source in sorted(sources):
        rows, errors = parse_file(root, inside(root, source))
        if errors:
            raise WorkbenchError('移行元の形式が不正です: '+source)
        kinds = {destination(r['type']) for r in rows}
        if len(kinds) == 1:
            dest = kinds.pop()
        elif '/architecture/' in source:
            dest = 'design.md'
        elif '/verification/' in source:
            dest = 'verification.md'
        else:
            dest = 'requirements.md'
        # A legacy file's prose applies to all its items: keep it in one section.
        # Mixed-kind authored files stay together so no prose is silently dropped.
        anchor = 'legacy-'+sha(source.encode())[:16]
        mapping[source] = destinations[dest]+'#'+anchor
        text = inside(root, source).read_text('utf-8')
        if 'upstream:section' in text:
            raise WorkbenchError('旧形式内に既存の節指定があります。先に確認してください: '+source)
        counts = {}
        out = []
        in_fence = False
        for line in text.splitlines():
            if line.lstrip().startswith('```'):
                in_fence = not in_fence
            heading = re.match(r'^#{1,6} +(.+?) *#*$', line) if not in_fence else None
            if heading:
                base = slug(heading[1]); n = counts.get(base, 0); counts[base] = n+1
                old = base+('-'+str(n) if n else '')
                ident = anchor+'--'+old
                mapping[source+'#'+old] = destinations[dest]+'#'+ident
                out.append('<a id="'+ident+'"></a>')
            out.append(line)
        bodies[source] = (dest, anchor, '\n'.join(out)+'\n')

    def rewrite(target: str, origin: str, new: str) -> str:
        u = urllib.parse.urlsplit(target)
        if u.scheme or u.netloc or target.startswith('/'):
            return target
        old_path = os.path.normpath(str(Path(origin).parent/urllib.parse.unquote(u.path))) if u.path else origin
        full = old_path+('#'+urllib.parse.unquote(u.fragment) if u.fragment else '')
        mapped = mapping.get(full)
        if mapped is None and old_path in set(records)|derived:
            mapped=mapping[old_path]+('#'+u.fragment if u.fragment else '')
        elif mapped is None and old_path in mapping:
            if u.fragment:
                raise WorkbenchError('移行先の節を解決できません: '+origin+' -> '+target)
            mapped = mapping[old_path]
        if mapped is None and u.path and not (root/old_path).exists():
            raise WorkbenchError('ローカルリンクの参照先がありません: '+origin+' -> '+target)
        dest, _, fragment = (mapped or full).partition('#')
        path = os.path.relpath(dest, Path(new).parent)
        return path+('?' + u.query if u.query else '')+('#'+fragment if fragment else '')

    outputs = {}
    for name, target in destinations.items():
        title = {'requirements.md':'要件', 'design.md':'設計', 'verification.md':'検証'}[name]
        lines = [f'# {config["system"]} {title}', '', '## 共通条件', '',
                 '移行元の本文とIDを節ごとに保持しています。承認履歴は元の内容に対する記録です。',
                 '移動した項目と依存項目は再レビューし、明示承認まで承認済みと判断しません。', '',
                 '<!-- upstream:section overview -->', '## 結論と確認してほしいこと', '',
                 '移行した節の内容を確認し、要点・判断待ち・未確認事項をここにまとめてください。',
                 '<!-- /upstream:section -->', '']
        for source, (dest, anchor, text) in bodies.items():
            if dest != name:
                continue
            text = LINK.sub(lambda m: m[1]+rewrite(m[2], source, target)+m[3], text)
            # Root-relative structured source strings are also rebased to canonical documents.
            for old, mapped in sorted(mapping.items(), key=lambda x: -len(x[0])):
                text = text.replace(json.dumps(old, ensure_ascii=False), json.dumps(mapped, ensure_ascii=False))
            lines += [f'<!-- upstream:section {anchor} -->', f'<a id="{anchor}"></a>',
                      f'<!-- Migrated from {source} -->', text, '<!-- /upstream:section -->', '']
        outputs[target] = '\n'.join(lines).encode()
        if len(outputs[target])>2_000_000:
            raise WorkbenchError('統合先が2MBを超えます。対象を整理してから移行してください: '+target)
    # Preserve custom/official docs. Update their links only when explicitly included.
    preserved = sorted(set(result['documents'])-sources-set(records)-derived)
    newconfig = dict(config, document_layout=COMPACT, workbench_version=VERSION)
    newconfig['required_docs'] = list(destinations.values())+[p for p in config.get('required_docs', []) if p not in sources and p not in known]
    newconfig['extra_docs'] = list(dict.fromkeys(mapping[p].split('#')[0] if p in sources else p for p in config.get('extra_docs', [])))
    moved = {r['id'] for r in result['items'] if r['_file'] in sources}
    affected = set(moved)
    while True:
        expanded = affected | {r['id'] for r in result['items'] if any(
            t in affected for rel, targets in r.get('links', {}).items() if rel in DEPENDENCY_LINKS for t in targets)}
        if expanded == affected:
            break
        affected = expanded
    latest = {e['id']:e for e in events}
    rereview = sorted(k for k in affected if latest.get(k, {}).get('event')=='approve'
                      or any(r['id']==k and r['status']=='approved' for r in result['items']))
    # Report remaining incoming links rather than silently altering custom/official prose.
    incoming = []
    incoming_docs=set(preserved)
    for folder,dirs,files in os.walk(root):
        dirs[:]=[d for d in dirs if d not in {'.git','node_modules','.venv','venv','runs','migrations','__pycache__'}
                 and not (Path(folder)/d).is_symlink()]
        for name in files:
            path=Path(folder)/name;rel=path.relative_to(root).as_posix()
            if (name.endswith('.md') and rel not in sources|set(records)|derived
                    and not path.is_symlink() and path.stat().st_size<=2_000_000):
                incoming_docs.add(rel)
    for source in sorted(incoming_docs):
        for m in LINK.finditer(inside(root, source).read_text('utf-8')):
            u = urllib.parse.urlsplit(m[2])
            if not u.scheme and u.path and os.path.normpath(str(Path(source).parent/urllib.parse.unquote(u.path))) in removed:
                incoming.append({'file':source, 'link':m[2]})
    for row in result['items']:
        if row['_file'] in removed:
            continue
        for value in row.get('sources',[]):
            if isinstance(value,str) and value.split('#')[0] in removed:
                incoming.append({'file':row['_file'],'link':value})
    if incoming:
        raise WorkbenchError('保持する文書から移行元へのリンクがあります。上流文書は--include-docで指定、公式specsはリンクを先に修正してください: '+json_text(incoming))
    newconfig['document_migration'] = {'backup':backup, 'links':mapping, 're_review_ids':rereview}
    outputs[cfgpath] = json_text(newconfig).encode()
    outputs.update({target:originals[source] for source,target in records.items()})
    preview = {'applied':False, 'documents':list(destinations.values()), 'sources':sorted(sources),
               'preserved':preserved, 'links':mapping, 'internal_records':records,
               'archived_derived_records':sorted(derived), 're_review_ids':rereview, 'backup':backup,
               'content':{p:outputs[p].decode() for p in destinations.values()}}
    if not apply:
        return preview
    with project_lock(root):
        if any(inside(root,p).read_bytes()!=data for p,data in originals.items()):
            raise WorkbenchError('移行プレビュー後に文書が変更されました。再実行してください')
        base = inside(root, backup)
        if base.exists():
            raise WorkbenchError('バックアップ先が既に存在します: '+backup)
        base.mkdir(parents=True)
        created = []
        try:
            for path,data in originals.items():
                atomic_write(inside(root,backup+'/original/'+path),data)
            atomic_write(base/'manifest.json',json_text({k:v for k,v in preview.items() if k!='content'}).encode())
            for path,data in outputs.items():
                if path not in originals:
                    created.append(path)
                atomic_write(inside(root,path),data)
            for path in sources|set(records)|derived:
                inside(root,path).unlink()
            after = inspect(root,'draft')
            if {r['id'] for r in after['items']} != {r['id'] for r in result['items']} or any(
                    f['code'] in {'DUPLICATE_ID','INVALID_JSON','INVALID_SCOPE','UNCLOSED_BLOCK'} for f in after['findings']):
                raise WorkbenchError('移行後のID/節の自己検査に失敗しました')
        except BaseException:
            for path in created:
                inside(root,path).unlink(missing_ok=True)
            for path,data in originals.items():
                atomic_write(inside(root,path),data)
            shutil.rmtree(base)
            raise
    preview['applied'] = True
    return preview
