"""Integration-anchor and transaction tests with explicit miniature upstream fixtures.

These do NOT substitute for the full repository's tests or the real Codex harness.
The production applier accepts only the exact GitHub blob SHAs inspected for this task.
"""
from __future__ import annotations
import importlib.util
from pathlib import Path
import subprocess
import sys
import tempfile
import unittest
from unittest.mock import patch

BASE=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(BASE/'overlay/tools/design-research/skill/scripts'))
spec=importlib.util.spec_from_file_location('apply_upgrade',BASE/'apply_upgrade.py')
upgrade=importlib.util.module_from_spec(spec);spec.loader.exec_module(upgrade)

HARNESS='''from pathlib import Path
import json
import argparse
HERE = Path(__file__).resolve().parent
VERSION = "2.0.1"
BASE = "Test fixture, not the complete upstream harness."

def role_prompt(role, state):
    instructions = {"producer": "Comparison research normally includes 2-3 distinct candidates and a current/minimal baseline."}
    inputs = {key: state.get(key) for key in
              ["run_id", "iteration", "config", "plan", "proposal", "review", "selected_issues",
               "evidence", "sources", "discovery", "input_review", "fixes"]}
    return BASE + "\\nROLE: " + role + "\\n" + instructions[role] + "\\nINPUT:\\n" + json.dumps(inputs)

def experiments(state, workspace, run_dir):
    proposal = state["proposal"]
    return proposal

def validate_review(value, state, workspace, run_dir):
    dossier = value.get("dossier")
    result = {"valid": True}
    if dossier:
        state["dossier"] = dossier
        state["ledger_validation"] = result
    return value

def gate_reasons(state):
    reasons = []
    return reasons

def config_from(args, project):
    return {"mode": args.mode, "reference_urls": args.reference_url}

def parser():
    p=argparse.ArgumentParser()
    commands=p.add_subparsers(dest="mode", required=True)
    for mode in ("research", "audit", "run"):
        sub=commands.add_parser(mode)
        sub.add_argument("--brief", required=True)
    return p
'''
REPORT='''from layout import MARKER, compact, record_path

def publish(state, workspace, run_dir):
    dossier=state.get('dossier')
    lines=['# 調査・検証報告', '## 結論と確認してほしいこと', '## 調査・比較・検証']
    if dossier:
        lines += ['', '### 主張と根拠', '']
    write(workspace,'report.md',lines)
    return lines

def publish_legacy(state, workspace, run_dir):
    report=[]
    if state.get('dossier'):
        report += ["", "## Claims and Evidence", ""]
    return report
'''
TEMPLATE='''<!-- Generated by design-research compact-v1 -->
# 調査・検証報告

実行状態: 下書き / {{DATE}}

## 結論と確認してほしいこと

調査課題: {{QUESTION}}

TODO: 結論・採用候補・判断待ち・未確認事項。実行前のため確認結果はありません。

## 調査・比較・検証

TODO: 対象範囲、条件、基準案と候補、共通の評価軸、実測と報告値の区別、根拠へのリンク。
内部のEvidence台帳は `.internal/evidence.json` に保存します。

## 残る確認

TODO: 未実行の確認、限界、再検討する条件。方式の採用承認は別途記録します。
'''


def setup(repo):
    data={upgrade.SKILL/'scripts/harness.py':HARNESS,upgrade.SKILL/'scripts/report.py':REPORT,
          upgrade.SKILL/'templates/report.md':TEMPLATE,
          upgrade.ROOT/'build_installer.py':'payload = {"version": "2.0.1"}\n',
          upgrade.ROOT/'install_design_research.py':'VERSION = "2.0.1"\n',
          upgrade.GENERATED:'original distribution\n'}
    for name in ('SKILL.md','references/roles.md','references/protocol.md','references/evidence-format.md'):
        data[upgrade.SKILL/name]='# Original fixture documentation\n'
    data[upgrade.SKILL/'SKILL.md'] += 'bash <skill-dir>/scripts/gan-harness.sh research --project <target> --brief test\n'
    for rel,body in data.items():
        p=repo/rel;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(body)
    return data


def fixture_hashes():
    return {upgrade.SKILL/'scripts/harness.py':upgrade.blob_sha(HARNESS.encode()),
            upgrade.SKILL/'scripts/report.py':upgrade.blob_sha(REPORT.encode())}


class UpgradeTests(unittest.TestCase):
    def test_actual_upstream_template_hash(self):
        self.assertEqual(upgrade.blob_sha(TEMPLATE.encode()),'a1c292f7477304cdb65d1c5cbb47b6ac43225566')

    def test_unknown_upstream_rejected_without_writes(self):
        with tempfile.TemporaryDirectory() as t:
            repo=Path(t);data=setup(repo)
            with self.assertRaisesRegex(ValueError,'inspected base'):upgrade.apply(repo,dry_run=True)
            for rel,body in data.items():self.assertEqual((repo/rel).read_text(),body)

    def test_patch_anchors_compile_and_include_profile_gate(self):
        h=upgrade.patch_harness(HARNESS);r=upgrade.patch_report(REPORT)
        compile(h,'harness.py','exec');compile(r,'report.py','exec')
        for token in ['prepare_preview(state','require_method_report(dossier','additional_gate_reasons(state)','"target_methods"','method_report_preview']:
            self.assertIn(token,h)
        self.assertIn('## 実験設定・結果・根拠',r)
        self.assertEqual(r.count('chapter_for_state(state, workspace, run_dir)'),3)

    def test_parser_defaults_five_and_profile_is_explicit(self):
        namespace={'__file__':'fixture.py'}
        exec(compile(upgrade.patch_harness(HARNESS),'fixture','exec'),namespace)
        args=namespace['parser']().parse_args(['research','--brief','test'])
        self.assertEqual(args.target_methods,5);self.assertEqual(args.report_profile,'comparison')
        args=namespace['parser']().parse_args(['research','--brief','test','--report-profile','proposed-method'])
        self.assertEqual(args.report_profile,'proposed-method')
        args=namespace['parser']().parse_args(['audit','--brief','test'])
        self.assertFalse(hasattr(args,'report_profile'))

    def test_missing_anchor_refused(self):
        with self.assertRaises(ValueError):upgrade.patch_harness(HARNESS.replace('return reasons','return []'))
        with self.assertRaises(ValueError):upgrade.patch_report(REPORT.replace('def publish(', 'def renamed('))

    def test_documentation_markers_are_idempotent(self):
        a=upgrade.append_block('Original prose\n','New text','report')
        self.assertEqual(a,upgrade.append_block(a,'New text','report'))
        self.assertIn('Original prose',a)
        with self.assertRaises(ValueError):upgrade.append_block('<!-- report:begin -->','x','report')

    def test_version_disagreement_is_refused(self):
        with tempfile.TemporaryDirectory() as t:
            repo=Path(t);setup(repo)
            (repo/upgrade.ROOT/'build_installer.py').write_text('payload={"version":"9.0.0"}\n')
            with patch.object(upgrade,'BASE_BLOBS',fixture_hashes()):
                with self.assertRaisesRegex(ValueError,'versions disagree'):upgrade.plan(repo)

    def test_bytecode_is_never_part_of_overlay(self):
        with tempfile.TemporaryDirectory() as t:
            root=Path(t);folder=root/'overlay'/'scripts'/'__pycache__';folder.mkdir(parents=True)
            (folder/'cache.pyc').write_bytes(b'fake cache')
            (root/'overlay'/'scripts'/'module.py').write_text('x=1\n')
            with patch.object(upgrade,'PACKAGE',root):
                paths=[q.relative_to(root/'overlay').as_posix() for q in upgrade.overlay_files()]
            self.assertEqual(paths,['scripts/module.py'])

    def test_dry_run_has_no_writes(self):
        with tempfile.TemporaryDirectory() as t:
            repo=Path(t);setup(repo)
            before={p.relative_to(repo):p.read_bytes() for p in repo.rglob('*') if p.is_file()}
            with patch.object(upgrade,'BASE_BLOBS',fixture_hashes()):
                self.assertTrue(upgrade.apply(repo,dry_run=True)['dry_run'])
            after={p.relative_to(repo):p.read_bytes() for p in repo.rglob('*') if p.is_file()}
            self.assertEqual(before,after)

    def test_user_custom_file_not_overwritten(self):
        with tempfile.TemporaryDirectory() as t:
            repo=Path(t);setup(repo);p=repo/upgrade.SKILL/'scripts/proposal_report.py';p.write_text('custom')
            with patch.object(upgrade,'BASE_BLOBS',fixture_hashes()):
                with self.assertRaisesRegex(ValueError,'Custom extension'):upgrade.apply(repo)
            self.assertEqual(p.read_text(),'custom')

    def test_symlink_component_refused(self):
        with tempfile.TemporaryDirectory() as t:
            root=Path(t);repo=root/'repo';repo.mkdir();setup(repo)
            p=repo/upgrade.SKILL/'scripts/report.py';p.unlink();p.symlink_to(root/'elsewhere')
            with patch.object(upgrade,'BASE_BLOBS',fixture_hashes()):
                with self.assertRaisesRegex(ValueError,'symlink'):upgrade.apply(repo,dry_run=True)

    def test_failed_builder_restores_every_changed_file(self):
        with tempfile.TemporaryDirectory() as t:
            repo=Path(t);setup(repo)
            before={p.relative_to(repo):p.read_bytes() for p in repo.rglob('*') if p.is_file()}
            with patch.object(upgrade,'BASE_BLOBS',fixture_hashes()),patch.object(upgrade.subprocess,'run',side_effect=subprocess.CalledProcessError(1,['mock-build'])):
                with self.assertRaises(subprocess.CalledProcessError):upgrade.apply(repo)
            after={p.relative_to(repo):p.read_bytes() for p in repo.rglob('*') if p.is_file()}
            self.assertEqual(before,after)

    def test_mock_build_transaction_and_reapply_are_idempotent(self):
        with tempfile.TemporaryDirectory() as t:
            repo=Path(t);setup(repo);calls=[]
            def build(cmd,**kw):
                calls.append(cmd)
                if cmd[-1].endswith('build_installer.py'):
                    (repo/upgrade.GENERATED).write_text('mock distribution, not a real installer\n')
                return subprocess.CompletedProcess(cmd,0)
            with patch.object(upgrade,'BASE_BLOBS',fixture_hashes()),patch.object(upgrade.subprocess,'run',side_effect=build):
                self.assertEqual(upgrade.apply(repo)['action'],'upgrade')
                self.assertEqual(upgrade.apply(repo)['action'],'skip')
                self.assertEqual(len(calls),3)
            (repo/upgrade.SKILL/'scripts/report.py').write_text('# local edit')
            with self.assertRaisesRegex(ValueError,'local changes'):upgrade.apply(repo)


if __name__=='__main__':unittest.main()
