#!/usr/bin/env python3
"""Build a deterministic single-file installer from maintained sources."""
import base64
import hashlib
import io
from pathlib import Path
import zipfile

ROOT = Path(__file__).resolve().parent
TARGET = ROOT.parents[1] / "install_codex_ux_stack.sh"
files = [ROOT / "install_ux_stack.py", ROOT / "sources.json"]
files += sorted(p for folder in ("skill", "browser", "ooui-design") for p in (ROOT / folder).rglob("*")
                if p.is_file() and "node_modules" not in p.parts and "__pycache__" not in p.parts)
bundle = io.BytesIO()
with zipfile.ZipFile(bundle, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as z:
    for path in files:
        info = zipfile.ZipInfo(path.relative_to(ROOT).as_posix(), date_time=(2026, 1, 1, 0, 0, 0))
        info.compress_type = zipfile.ZIP_DEFLATED
        info.external_attr = (0o755 if path.suffix in (".py", ".sh", ".cjs") else 0o644) << 16
        z.writestr(info, path.read_bytes())
data = bundle.getvalue()
header = """#!/usr/bin/env bash
set -euo pipefail
# Generated by tools/codex-ux-stack/build_installer.py; edit the maintained sources.
# No arguments installs. --dry-run only plans. Run --help for all options.
command -v python3 >/dev/null 2>&1 || { printf '%s\\n' 'Python 3.10+ is required.' >&2; exit 1; }
UX_STACK_TEMP="$(mktemp -d)"
trap 'rm -rf -- "$UX_STACK_TEMP"' EXIT
python3 - "$0" "$UX_STACK_TEMP" <<'UX_STACK_BOOTSTRAP'
import base64,hashlib,io,sys,zipfile
from pathlib import Path
if sys.version_info < (3,10):
    raise SystemExit("Python 3.10+ is required")
src=Path(sys.argv[1]).read_text()
data=base64.b64decode(src.split("\\n__UX_STACK_PAYLOAD__\\n",1)[1],validate=False)
if hashlib.sha256(data).hexdigest() != "BUNDLE_SHA":
    raise SystemExit("Embedded payload checksum mismatch")
root=Path(sys.argv[2]).resolve()
with zipfile.ZipFile(io.BytesIO(data)) as archive:
    for info in archive.infolist():
        p=root/info.filename
        if not p.resolve().is_relative_to(root):
            raise SystemExit("Invalid embedded payload path")
        p.parent.mkdir(parents=True,exist_ok=True)
        p.write_bytes(archive.read(info))
        p.chmod(info.external_attr >> 16)
UX_STACK_BOOTSTRAP
python3 "$UX_STACK_TEMP/install_ux_stack.py" "$@"
exit $?
__UX_STACK_PAYLOAD__
"""
header = header.replace("BUNDLE_SHA", hashlib.sha256(data).hexdigest())
encoded = base64.b64encode(data).decode()
TARGET.write_text(header + "\n".join(encoded[n:n+100] for n in range(0, len(encoded), 100)) + "\n")
TARGET.chmod(0o755)
print("Built", TARGET.name, hashlib.sha256(data).hexdigest())
