#!/usr/bin/env python3
"""Deterministically embed maintained Design Research sources in one Bash file."""
from __future__ import annotations

import argparse
import base64
import hashlib
import json
from pathlib import Path
import zlib

ROOT = Path(__file__).resolve().parent
TARGET = ROOT.parents[1] / "install_design_research.sh"


def bundle():
    files = {}
    for path in sorted((ROOT / "skill").rglob("*")):
        if "__pycache__" in path.parts or path.suffix == ".pyc":
            continue
        if path.is_symlink():
            raise ValueError("Payload source cannot be a symlink")
        if not path.is_file():
            continue
        name = path.relative_to(ROOT / "skill").as_posix()
        data = path.read_bytes()
        files[name] = {"sha256": hashlib.sha256(data).hexdigest(),
                       "data_b64": base64.b64encode(data).decode(),
                       "mode": 0o755 if name in
                       {"scripts/research.py", "scripts/harness.py", "scripts/gan-harness.sh"} else 0o644}
    payload = {"schema_version": 1, "name": "design-research", "version": "2.0.1", "files": files}
    data = zlib.compress(json.dumps(payload, ensure_ascii=False, sort_keys=True,
                                   separators=(",", ":")).encode(), level=9)
    return payload, data


def render():
    _, data = bundle()
    program = (ROOT / "install_design_research.py").read_text("utf-8").replace(
        "__PAYLOAD_SHA256__", hashlib.sha256(data).hexdigest())
    dollar = chr(36)
    header = f"""#!/usr/bin/env bash
set -euo pipefail
# Generated by tools/design-research/build_installer.py; edit maintained sources.
# No arguments installs. --dry-run plans without changing the destination.
PYTHON_BIN="{dollar}{{PYTHON_BIN:-python3}}"
command -v "$PYTHON_BIN" >/dev/null 2>&1 || {{
  printf '%s\\n' 'Python 3.10+ is required.' >&2
  exit 1
}}
"$PYTHON_BIN" - "$0" "$@" <<'__INSTALLER_PY__'
"""
    encoded = base64.b64encode(data).decode()
    return (header + program + "\n__INSTALLER_PY__\nexit $?\n\n__DESIGN_RESEARCH_PAYLOAD__\n" +
            "\n".join(encoded[n:n + 100] for n in range(0, len(encoded), 100)) + "\n")


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Verify tracked distribution matches sources")
    parser.add_argument("--output", type=Path, default=TARGET)
    args = parser.parse_args(argv)
    result = render()
    if args.check:
        if not args.output.is_file() or args.output.read_text("utf-8") != result:
            parser.exit(1, "Design Research distribution differs from maintained sources\n")
        print("Design Research distribution matches maintained sources")
    else:
        args.output.write_text(result, "utf-8")
        args.output.chmod(0o755)
        print("Built", args.output.name)


if __name__ == "__main__":
    main()
