"""Human report layout and machine-record locations, with explicit legacy opt-in migration."""
from pathlib import Path
import json

from runtime import Blocked, atomic_json, regular_path

LEGACY_REPORTS = ('design-research.md', 'decision.md', 'review.md', 'fix-report.md', 'reference-implementations.md')
RECORDS = ('status.json', 'evidence.json', 'research-log.json')
MARKER = '<!-- Generated by design-research compact-v1 -->'


def compact(workspace):
    path = regular_path(Path(workspace)/'.internal/layout.json')
    if not path.exists():
        return False
    value = json.loads(path.read_text('utf-8'))
    if value != {'schema_version':1, 'generator':'design-research', 'layout':'compact-v1'}:
        raise Blocked('Unrecognized document layout record')
    return True


def initialize(workspace):
    workspace = Path(workspace)
    if compact(workspace):
        return True
    if any(regular_path(workspace/name).exists() for name in (*LEGACY_REPORTS, *RECORDS)):
        return False
    if regular_path(workspace/'report.md').exists():
        raise Blocked('Existing report.md has no layout record; review migration instead of overwriting it')
    atomic_json(workspace/'.internal/layout.json',
                {'schema_version':1, 'generator':'design-research', 'layout':'compact-v1'})
    return True


def record_path(workspace, name):
    workspace = Path(workspace)
    return regular_path(workspace/('.internal' if compact(workspace) else '')/name)
